[env]
# Windows icon path used by build.rs when the `windows-icon` feature is enabled
APP_ICON = 'assets\app.ico'

[features]
windows-icon = ["iced/windows-icon"]

[alias]
# Build with Windows icon feature enabled
build-icon = "build --release --features windows-icon"

# Run with Windows icon feature enabled
run-icon = "run --release --features windows-icon"