name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build (release)
        run: cargo build --release --features windows-icon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-hash-windows
          path: |
            target/release/rust-hash.exe

  create-release:
    runs-on: ubuntu-latest
    needs: build-windows
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: rust-hash-windows

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rust-hash.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
